apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  selector:
    matchLabels:
      io.kompose.service: app
  replicas: 2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      initContainers:
        - args:
            - manage.py
            - db
            - upgrade
          env:
            - name: APP_SETTINGS
              value: config.DevelopmentConfig
            - name: DBPASS
              valueFrom:
                secretKeyRef:
                  name: fbe-secret
                  key: dbpass
            - name: DATABASE_URL
              value: postgresql://wordcount_dbadmin:MYPASS@db/wordcount_dev
            - name: POSTGRES_DB
              value: db
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          image: mdrahali/flask-by-example:v1
          name: migrations
          resources: {}
      containers:
      - args:
        - manage.py
        - runserver
        - --host=0.0.0.0
        env:
        - name: APP_SETTINGS
          value: config.DevelopmentConfig
        - name: DATABASE_URL
          value: postgresql://wordcount_dbadmin:MYPASS@db/wordcount_dev
        - name: POSTGRES_DB
          value: db
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        - name: REDISTOGO_URL
          value: redis://redis:6379
        image: mdrahali/flask-by-example:v1
        name: app
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
