apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  selector:
    matchLabels:
      io.kompose.service: worker
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: worker
    spec:
      containers:
      - args:
        - worker.py
        env:
        - name: APP_SETTINGS
          value: config.DevelopmentConfig
        - name: DATABASE_URL
          value: postgresql://wordcount_dbadmin:MYPASS@db/wordcount_dev
        - name: POSTGRES_DB
          value: db
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        - name: REDISTOGO_URL
          value: redis://redis:6379
        image: mdrahali/flask-by-example:v1
        name: worker
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: myregistrykey
status: {}
